services:
  db:
    container_name: yc-db
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
#      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yc